// Copyright 2022 Dhiraj Wishal
// SPDX-License-Identifier: Apache-2.0

#ifndef VERTEX_INPUT_DEFINES_HLSL
#define VERTEX_INPUT_DEFINES_HLSL

#define XENON_VERTEX_INPUT_VERTEX_POSITION_LOCATION					0
#define XENON_VERTEX_INPUT_VERTEX_NORMAL_LOCATION					1
#define XENON_VERTEX_INPUT_VERTEX_TANGENT_LOCATION					2

#define XENON_VERTEX_INPUT_VERTEX_COLOR_0_LOCATION					3
#define XENON_VERTEX_INPUT_VERTEX_COLOR_1_LOCATION					4
#define XENON_VERTEX_INPUT_VERTEX_COLOR_2_LOCATION					5
#define XENON_VERTEX_INPUT_VERTEX_COLOR_3_LOCATION					6
#define XENON_VERTEX_INPUT_VERTEX_COLOR_4_LOCATION					7
#define XENON_VERTEX_INPUT_VERTEX_COLOR_5_LOCATION					8
#define XENON_VERTEX_INPUT_VERTEX_COLOR_6_LOCATION					9
#define XENON_VERTEX_INPUT_VERTEX_COLOR_7_LOCATION					10

#define XENON_VERTEX_INPUT_VERTEX_TEXTURE_COORDINATE_0_LOCATION		11
#define XENON_VERTEX_INPUT_VERTEX_TEXTURE_COORDINATE_1_LOCATION		12
#define XENON_VERTEX_INPUT_VERTEX_TEXTURE_COORDINATE_2_LOCATION		13
#define XENON_VERTEX_INPUT_VERTEX_TEXTURE_COORDINATE_3_LOCATION		14
#define XENON_VERTEX_INPUT_VERTEX_TEXTURE_COORDINATE_4_LOCATION		15
#define XENON_VERTEX_INPUT_VERTEX_TEXTURE_COORDINATE_5_LOCATION		16
#define XENON_VERTEX_INPUT_VERTEX_TEXTURE_COORDINATE_6_LOCATION		17
#define XENON_VERTEX_INPUT_VERTEX_TEXTURE_COORDINATE_7_LOCATION		18

#define XENON_VERTEX_INPUT_VERTEX_JOINT_INDICES_LOCATION			19
#define XENON_VERTEX_INPUT_VERTEX_JOINT_WEIGHT_LOCATION				20

#define XENON_VERTEX_INPUT_INSTANCE_POSITION_LOCATION				21
#define XENON_VERTEX_INPUT_INSTANCE_ROTATION_LOCATION				22
#define XENON_VERTEX_INPUT_INSTANCE_SCALE_LOCATION					23
#define XENON_VERTEX_INPUT_INSTANCE_ID_LOCATION						24

#endif // VERTEX_INPUT_DEFINES_HLSL